Spring:
  jpa:
    # 전송 쿼리 확인
    show-sql: true # 애플리케이션 실행 과정에 데이터베이스에 쿼리할 일이 있으면 실행 구문을 모두 보여주는 옵션
    properties:
      hibernate:
        format_sql: true # 애플리케이션 실행 과정에 데이터베이스에 쿼리할 일이 있으면 실행 구문을 모두 보여주는 옵션

    # 애플리케이션을 실행할 때 테이블을 생성하고 data.sql 파일에 있는 쿼리를 실행하도록 하는 옵션
    defer-datasource-initialization: true